name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests for all apps
        run: |
          # Use find and xargs to discover and execute tests for all subdirectories in "tests"
          find tests -mindepth 1 -type d -print0 | xargs -0 -I {} sh -c 'echo "Running tests in {}"; cd {}; python -m unittest discover'
